Introduce seed service
ExtensionEngine/app-starter pull request #21
Opened 2021-10-15 14:14 UTC by lukasaric

This PR adds:

- Seed service
- `users` seed

2021-10-21 10:48 UTC, MiroDojkic requested changes

2021-10-21 10:48 UTC, MiroDojkic commented on server/services/seed.ts
> +import { Config } from '../config';
This logic is tied to the Database provider so should we move it to `shared/database/seed`?

2021-10-21 10:48 UTC, MiroDojkic commented on server/shared/database/seeds/users.ts
> +  });
This logic seems a bit hard to read. Why not separate admin and user seeding logic - we could have completely different credentials too, i.e. `admin@example.org`?

2021-10-21 10:48 UTC, MiroDojkic commented on server/shared/database/seeds/index.ts
> +import { EntityManager } from '@mikro-orm/postgresql';
Where is this used?

2021-10-21 12:02 UTC, lukasaric commented on server/shared/database/seeds/index.ts
> +import { EntityManager } from '@mikro-orm/postgresql';
It's used below as `em` param  type.

2021-10-21 12:07 UTC, lukasaric commented on server/shared/database/seeds/users.ts
> +  });
👍

2021-10-22 08:42 UTC, MiroDojkic approved these changes

2021-10-22 08:42 UTC, merged